package chikoski:hello-world;

interface greet {
    hello-world: func() -> string;
    greet: func(name: string) -> string;
}

/// An example world for the component to target.
world example {
    export greet;
}
    
